export default ACTIONS = {
  ADD_TASK: 'ADD_TASK',
  DELETE_TASK: 'DELETE_TASK',
  TOGGLE_TASK: 'TOGGLE_TASK',
  API_SUCCESS: 'API_SUCCESS',
  API_LOADING: 'API_LOADING',
  API_ERROR: 'API_ERROR',
};
